/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.emtecinc;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.DefaultCellEditor;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.table.TableColumn;

/**
 *
 * @author Randall.Miller
 */
public class AcceptReject extends javax.swing.JDialog {

    /**
     * Creates new form AcceptReject
     */
    public AcceptReject(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        populateJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgAndOr = new javax.swing.ButtonGroup();
        pnlAndOr = new javax.swing.JPanel();
        rblAnd = new javax.swing.JRadioButton();
        rblOr = new javax.swing.JRadioButton();
        lblCol = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAccRej = new javax.swing.JTable();
        btnNextField = new javax.swing.JButton();
        btnPrevField1 = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bgAndOr.add(rblAnd);
        rblAnd.setText("And");

        bgAndOr.add(rblOr);
        rblOr.setText("Or");

        javax.swing.GroupLayout pnlAndOrLayout = new javax.swing.GroupLayout(pnlAndOr);
        pnlAndOr.setLayout(pnlAndOrLayout);
        pnlAndOrLayout.setHorizontalGroup(
            pnlAndOrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAndOrLayout.createSequentialGroup()
                .addComponent(rblOr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rblAnd)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlAndOrLayout.setVerticalGroup(
            pnlAndOrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAndOrLayout.createSequentialGroup()
                .addGroup(pnlAndOrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rblOr)
                    .addComponent(rblAnd))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblCol.setText("Column: ");

        tblAccRej.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "<HTML>Accept<BR>Reject</HTML>", "Type", "Criteria", "Condition", "<HTML>Case<BR>Sensitive<HTML>"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAccRej);

        btnNextField.setText("Next Field");

        btnPrevField1.setText("Prev Field");

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.setToolTipText("");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlAndOr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCol)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 135, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnPrevField1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNextField)
                                .addGap(118, 118, 118))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnOK)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancel)
                                .addGap(134, 134, 134))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCol)
                .addGap(3, 3, 3)
                .addComponent(pnlAndOr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNextField)
                    .addComponent(btnPrevField1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK)
                    .addComponent(btnCancel))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_btnCancelActionPerformed

    
    private void populateJTable()
    {
        
        TableColumn colAccRej = tblAccRej.getColumnModel().getColumn(0);
        TableColumn colType = tblAccRej.getColumnModel().getColumn(1);
        TableColumn colCond = tblAccRej.getColumnModel().getColumn(3);
        //TableColumn colCase = tblAccRej.getColumnModel().getColumn(4);
 
        
        JComboBox cbAccRej = new JComboBox();
        cbAccRej.addItem("Accept");
        cbAccRej.addItem("Reject");
        colAccRej.setCellEditor(new DefaultCellEditor(cbAccRej));
        
        JComboBox cbType = new JComboBox();
        cbType.addItem("String");
        cbType.addItem("Number");
        colType.setCellEditor(new DefaultCellEditor(cbType));
        
        JComboBox cbCond = new JComboBox();
        //JCheckBox cbxCase = new JCheckBox();
        //cbxCase.setEnabled(false);
        
        cbType.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                
                cbCond.removeAllItems();
                cbCond.addItem("Equals");
                cbCond.addItem("Not Equals");
                
                if (cbType.getSelectedIndex() != -1){
                    
                    if (cbType.getSelectedItem().equals("String")){
                        cbCond.addItem("Contains");
                        cbCond.addItem("Does Not Contain");
                        //cbxCase.setEnabled(true);
                        
                    } else {
                        cbCond.addItem("Greater Than");
                        cbCond.addItem("Greater Than or Equal");
                        cbCond.addItem("Less Than");
                        cbCond.addItem("Less Than or Equal");
                        //cbxCase.setEnabled(false);
                    }
                }
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
        
        
        colCond.setCellEditor(new DefaultCellEditor(cbCond));
        //colCase.setCellEditor(new DefaultCellEditor(cbxCase));
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcceptReject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcceptReject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcceptReject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcceptReject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AcceptReject dialog = new AcceptReject(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgAndOr;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnNextField;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnPrevField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCol;
    private javax.swing.JPanel pnlAndOr;
    private javax.swing.JRadioButton rblAnd;
    private javax.swing.JRadioButton rblOr;
    private javax.swing.JTable tblAccRej;
    // End of variables declaration//GEN-END:variables
}
