/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.emtecinc;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;

/**
 *
 * @author Randall.Miller
 */
public class PBCSAdmin extends javax.swing.JFrame {
    public File flSourceFile;
    pbcsDLManager dlManager = new pbcsDLManager();
    static int[] arrDataColumn;
    static String[] arrPrefix;
    static String[] arrSuffix;
    static String[] arrFind;
    static String[] arrReplace;
    
    /**
     * Creates new form PBCSAdmin
     */
    public PBCSAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgDelimiter = new javax.swing.ButtonGroup();
        MainTabbedPane = new javax.swing.JTabbedPane();
        tabDLMgr = new javax.swing.JPanel();
        pnlDSMgmt = new javax.swing.JPanel();
        lblDelim = new javax.swing.JLabel();
        rbComma = new javax.swing.JRadioButton();
        rbSpace = new javax.swing.JRadioButton();
        rbTab = new javax.swing.JRadioButton();
        rbCustom = new javax.swing.JRadioButton();
        txtCustDelim = new javax.swing.JTextField();
        btnLoadSQL = new javax.swing.JButton();
        lblDisplayRows = new javax.swing.JLabel();
        txtDisplayRows = new javax.swing.JTextField();
        lblStartRow = new javax.swing.JLabel();
        txtStartRow = new javax.swing.JTextField();
        lblDisplayRows2 = new javax.swing.JLabel();
        txtHeaderRows = new javax.swing.JTextField();
        btnBrowse = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        pnlColProps = new javax.swing.JPanel();
        lblColumn = new javax.swing.JLabel();
        lblPrefix = new javax.swing.JLabel();
        txtPrefix = new javax.swing.JTextField();
        lblSuffix = new javax.swing.JLabel();
        txtSuffix = new javax.swing.JTextField();
        lblFind = new javax.swing.JLabel();
        txtFind = new javax.swing.JTextField();
        lblReplace = new javax.swing.JLabel();
        txtReplace = new javax.swing.JTextField();
        btnUpdateField = new javax.swing.JButton();
        lblColName = new javax.swing.JLabel();
        txtColName = new javax.swing.JTextField();
        cbData = new javax.swing.JCheckBox();
        btnPrevField = new javax.swing.JButton();
        btnNextField = new javax.swing.JButton();
        btnAddColumn = new javax.swing.JButton();
        btnColumnActions = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        tabFSMgr = new javax.swing.JPanel();

        rbComma.doClick();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainTabbedPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        tabDLMgr.setPreferredSize(new java.awt.Dimension(1450, 512));

        pnlDSMgmt.setBackground(new java.awt.Color(153, 204, 255));
        pnlDSMgmt.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Data Source Properties", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        lblDelim.setText("Delimiter");

        btgDelimiter.add(rbComma);
        rbComma.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        rbComma.setText("Comma");

        btgDelimiter.add(rbSpace);
        rbSpace.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        rbSpace.setText("Space");

        btgDelimiter.add(rbTab);
        rbTab.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        rbTab.setText("Tab");

        btgDelimiter.add(rbCustom);
        rbCustom.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        rbCustom.setText("Custom");

        btnLoadSQL.setText("Load SQL");
        btnLoadSQL.setEnabled(false);

        lblDisplayRows.setText("Rows to Display");

        txtDisplayRows.setText("500");

        lblStartRow.setText("Start Row");
        lblStartRow.setToolTipText("");

        txtStartRow.setText("1");

        lblDisplayRows2.setText("Header Rows");

        txtHeaderRows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeaderRowsActionPerformed(evt);
            }
        });

        btnBrowse.setText("Load File");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDSMgmtLayout = new javax.swing.GroupLayout(pnlDSMgmt);
        pnlDSMgmt.setLayout(pnlDSMgmtLayout);
        pnlDSMgmtLayout.setHorizontalGroup(
            pnlDSMgmtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDSMgmtLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDSMgmtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlDSMgmtLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnBrowse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLoadSQL))
                    .addComponent(lblDelim, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlDSMgmtLayout.createSequentialGroup()
                        .addComponent(lblDisplayRows)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDisplayRows, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDSMgmtLayout.createSequentialGroup()
                        .addGroup(pnlDSMgmtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDisplayRows2)
                            .addComponent(lblStartRow))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlDSMgmtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtStartRow)
                            .addGroup(pnlDSMgmtLayout.createSequentialGroup()
                                .addComponent(txtHeaderRows, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50))))
                    .addGroup(pnlDSMgmtLayout.createSequentialGroup()
                        .addGroup(pnlDSMgmtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlDSMgmtLayout.createSequentialGroup()
                                .addComponent(rbComma, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbTab, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlDSMgmtLayout.createSequentialGroup()
                                .addComponent(rbSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbCustom, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCustDelim)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDSMgmtLayout.setVerticalGroup(
            pnlDSMgmtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDSMgmtLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDSMgmtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLoadSQL)
                    .addComponent(btnBrowse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDelim, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDSMgmtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rbComma, javax.swing.GroupLayout.PREFERRED_SIZE, 18, Short.MAX_VALUE)
                    .addComponent(rbTab, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDSMgmtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbCustom, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCustDelim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDSMgmtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDisplayRows)
                    .addComponent(txtDisplayRows, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(pnlDSMgmtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStartRow)
                    .addComponent(txtStartRow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDSMgmtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDisplayRows2)
                    .addComponent(txtHeaderRows, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        lblDelim.getAccessibleContext().setAccessibleName("lblDelim");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setDragEnabled(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTable1PropertyChange(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        btnRefresh.setText("Refresh Table");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        pnlColProps.setBackground(new java.awt.Color(204, 204, 204));
        pnlColProps.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlColProps.setForeground(new java.awt.Color(204, 204, 204));

        lblColumn.setText("Select Column to Edit");

        lblPrefix.setBackground(new java.awt.Color(0, 0, 0));
        lblPrefix.setText("Prefix");
        lblPrefix.setMaximumSize(new java.awt.Dimension(35, 16));
        lblPrefix.setMinimumSize(new java.awt.Dimension(35, 16));
        lblPrefix.setPreferredSize(new java.awt.Dimension(35, 16));

        txtPrefix.setEnabled(false);
        txtPrefix.setMaximumSize(new java.awt.Dimension(60, 24));
        txtPrefix.setMinimumSize(new java.awt.Dimension(60, 24));

        lblSuffix.setText("Suffix");
        lblSuffix.setMaximumSize(new java.awt.Dimension(35, 16));
        lblSuffix.setMinimumSize(new java.awt.Dimension(35, 16));
        lblSuffix.setPreferredSize(new java.awt.Dimension(35, 16));

        txtSuffix.setEnabled(false);
        txtSuffix.setMaximumSize(new java.awt.Dimension(60, 24));
        txtSuffix.setMinimumSize(new java.awt.Dimension(60, 24));

        lblFind.setText("Find");
        lblFind.setMaximumSize(new java.awt.Dimension(35, 16));
        lblFind.setMinimumSize(new java.awt.Dimension(35, 16));
        lblFind.setPreferredSize(new java.awt.Dimension(35, 16));

        txtFind.setEnabled(false);
        txtFind.setMaximumSize(new java.awt.Dimension(60, 24));
        txtFind.setMinimumSize(new java.awt.Dimension(60, 24));
        txtFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFindActionPerformed(evt);
            }
        });

        lblReplace.setText("Replace");
        lblReplace.setMaximumSize(new java.awt.Dimension(35, 16));
        lblReplace.setMinimumSize(new java.awt.Dimension(35, 16));
        lblReplace.setPreferredSize(new java.awt.Dimension(35, 16));

        txtReplace.setEnabled(false);
        txtReplace.setMaximumSize(new java.awt.Dimension(60, 24));
        txtReplace.setMinimumSize(new java.awt.Dimension(60, 24));

        btnUpdateField.setText("Update Field");
        btnUpdateField.setEnabled(false);
        btnUpdateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateFieldActionPerformed(evt);
            }
        });

        lblColName.setBackground(new java.awt.Color(0, 0, 0));
        lblColName.setText("Column Name");
        lblColName.setMaximumSize(new java.awt.Dimension(35, 16));
        lblColName.setMinimumSize(new java.awt.Dimension(35, 16));
        lblColName.setPreferredSize(new java.awt.Dimension(35, 16));

        txtColName.setEnabled(false);
        txtColName.setMaximumSize(new java.awt.Dimension(60, 24));
        txtColName.setMinimumSize(new java.awt.Dimension(60, 24));
        txtColName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColNameActionPerformed(evt);
            }
        });

        cbData.setText("Data Field");
        cbData.setEnabled(false);
        cbData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDataActionPerformed(evt);
            }
        });

        btnPrevField.setText("Prev Field");
        btnPrevField.setEnabled(false);
        btnPrevField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevFieldActionPerformed(evt);
            }
        });

        btnNextField.setText("Next Field");
        btnNextField.setEnabled(false);
        btnNextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlColPropsLayout = new javax.swing.GroupLayout(pnlColProps);
        pnlColProps.setLayout(pnlColPropsLayout);
        pnlColPropsLayout.setHorizontalGroup(
            pnlColPropsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlColPropsLayout.createSequentialGroup()
                .addGroup(pnlColPropsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblColumn)
                    .addGroup(pnlColPropsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlColPropsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlColPropsLayout.createSequentialGroup()
                                .addComponent(btnPrevField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnNextField))
                            .addComponent(cbData)
                            .addGroup(pnlColPropsLayout.createSequentialGroup()
                                .addGroup(pnlColPropsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblFind, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                    .addComponent(lblSuffix, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPrefix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblColName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblReplace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlColPropsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtColName, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                    .addComponent(txtPrefix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSuffix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtFind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtReplace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(pnlColPropsLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btnUpdateField)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlColPropsLayout.setVerticalGroup(
            pnlColPropsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlColPropsLayout.createSequentialGroup()
                .addComponent(lblColumn)
                .addGap(7, 7, 7)
                .addGroup(pnlColPropsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtColName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlColPropsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrefix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrefix, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlColPropsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSuffix, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSuffix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlColPropsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFind, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlColPropsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReplace, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtReplace, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdateField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlColPropsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrevField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        btnAddColumn.setText("Add Simple Column");
        btnAddColumn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddColumnActionPerformed(evt);
            }
        });

        btnColumnActions.setEnabled(false);
        btnColumnActions.setLabel("Column Actions");
        btnColumnActions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColumnActionsActionPerformed(evt);
            }
        });

        btnExport.setText("Export to File");
        btnExport.setEnabled(false);
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabDLMgrLayout = new javax.swing.GroupLayout(tabDLMgr);
        tabDLMgr.setLayout(tabDLMgrLayout);
        tabDLMgrLayout.setHorizontalGroup(
            tabDLMgrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDLMgrLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabDLMgrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlDSMgmt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlColProps, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabDLMgrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(tabDLMgrLayout.createSequentialGroup()
                        .addGroup(tabDLMgrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabDLMgrLayout.createSequentialGroup()
                                .addComponent(btnRefresh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddColumn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnColumnActions)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExport))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tabDLMgrLayout.setVerticalGroup(
            tabDLMgrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDLMgrLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabDLMgrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabDLMgrLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabDLMgrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRefresh)
                            .addComponent(btnAddColumn)
                            .addComponent(btnColumnActions)
                            .addComponent(btnExport))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(tabDLMgrLayout.createSequentialGroup()
                        .addComponent(pnlDSMgmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlColProps, javax.swing.GroupLayout.PREFERRED_SIZE, 298, Short.MAX_VALUE)))
                .addContainerGap())
        );

        MainTabbedPane.addTab("Data Load Manager", tabDLMgr);

        javax.swing.GroupLayout tabFSMgrLayout = new javax.swing.GroupLayout(tabFSMgr);
        tabFSMgr.setLayout(tabFSMgrLayout);
        tabFSMgrLayout.setHorizontalGroup(
            tabFSMgrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1450, Short.MAX_VALUE)
        );
        tabFSMgrLayout.setVerticalGroup(
            tabFSMgrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 557, Short.MAX_VALUE)
        );

        MainTabbedPane.addTab("File System Manager", tabFSMgr);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        updateColProps();
    }//GEN-LAST:event_jTable1MouseClicked

    public void updateColProps(){
        jTable1.setCellSelectionEnabled(false);
        jTable1.setRowSelectionAllowed(false);
        jTable1.setColumnSelectionAllowed(true);
        jTable1.getSelectedColumn();
        jTable1.setRowSelectionInterval(0, jTable1.getRowCount()-1);
        lblColumn.setText(jTable1.getColumnModel().getColumn(jTable1.getSelectedColumn()).getHeaderValue().toString() + " Properties");
        txtColName.setText(jTable1.getColumnModel().getColumn(jTable1.getSelectedColumn()).getHeaderValue().toString());
       // txtColName.setText(jTable1.getColumnName(jTable1.getSelectedColumn()));
        btnColumnActions.setEnabled(true);
        // Set Column Property Objects to Enabled
        btnUpdateField.setEnabled(true);
        cbData.setEnabled(true);
        txtColName.setEnabled(true);
        txtPrefix.setEnabled(true);
        txtSuffix.setEnabled(true);
        txtFind.setEnabled(true);
        txtReplace.setEnabled(true);        
        
        if (jTable1.getSelectedColumn() == 0){
            btnPrevField.setEnabled(false);
        } else {
            btnPrevField.setEnabled(true);
        }
        
        if (jTable1.getSelectedColumn() == jTable1.getColumnCount() - 1){
            btnNextField.setEnabled(false);
        } else {
            btnNextField.setEnabled(true);
        }
        
        // Set Data Checkbox based on array
        if (arrDataColumn[jTable1.getSelectedColumn()] == 1) {
            cbData.setSelected(true);
        } else {
            cbData.setSelected(false);
        }
        //Set Text Boxes based on Array
        txtPrefix.setText(arrPrefix[jTable1.getSelectedColumn()]);
        txtSuffix.setText(arrSuffix[jTable1.getSelectedColumn()]);
        txtFind.setText(arrFind[jTable1.getSelectedColumn()]);
        txtReplace.setText(arrReplace[jTable1.getSelectedColumn()]);
        
        
    }
    
    
    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        try{
            
            String strDelim = "";
            if (rbComma.isSelected()){
                strDelim = ",";
            } else if (rbTab.isSelected()){
                strDelim = "\t";
            } else if (rbSpace.isSelected()){
                strDelim = " ";
            } else if (rbCustom.isSelected()){
                strDelim = txtCustDelim.getText();
            }
            
            DefaultTableModel model;
            if (txtHeaderRows.getText().length() < 1) {
                //model = getModelFromCsvFile(this.flSourceFile, strDelim, false);
                model = dlManager.getModelFromCsvFile(this.flSourceFile, strDelim, false, Integer.parseInt(txtDisplayRows.getText()), Integer.parseInt(txtStartRow.getText()));
            } else {
                model = dlManager.getModelFromCsvFile(this.flSourceFile, strDelim, true, Integer.parseInt(txtDisplayRows.getText()), Integer.parseInt(txtStartRow.getText()));
            }
            jTable1.setModel(model);
        } catch (Throwable x) {
            
            JOptionPane.showMessageDialog(this.getParent(), "Error: " + x.getMessage());
        }
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void txtFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFindActionPerformed

    private void btnUpdateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateFieldActionPerformed
        // TODO add your handling code here:
        //arrDataColumn = new int[jTable1.getColumnCount()];
        TableModel model = dlManager.findReplaceField(jTable1, txtFind.getText(), txtReplace.getText(), txtPrefix.getText(), txtSuffix.getText());
        if (txtColName.getText() != null) {
            dlManager.renameTableColumn(jTable1, txtColName.getText());
        }
        if (txtPrefix.getText() != null) {
            arrPrefix[jTable1.getSelectedColumn()] = txtPrefix.getText();
        }
        if (txtSuffix.getText() != null) {
            arrSuffix[jTable1.getSelectedColumn()] = txtSuffix.getText();
        }
        if (txtFind.getText() != null) {
            arrFind[jTable1.getSelectedColumn()] = txtFind.getText();
        }
        if (txtReplace.getText() != null) {
            arrReplace[jTable1.getSelectedColumn()] = txtReplace.getText();
        }
        if (cbData.isSelected()) {
            arrDataColumn[jTable1.getSelectedColumn()] = 1;
        }
    }//GEN-LAST:event_btnUpdateFieldActionPerformed

    private void btnAddColumnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddColumnActionPerformed
        // TODO add your handling code here:
        TableColumn simpleColumn = new TableColumn();
        JTextField columnName = new JTextField();
        JTextField columnData = new JTextField();
        Object[] newField = {
            "Column Name: ", columnName,
            "Column Data: ", columnData
        };
        //String columnData = new String(JOptionPane.showInputDialog(this.getParent(), "Enter Column Data"));
        int option = JOptionPane.showConfirmDialog(this.getParent(), newField, "Column Information", JOptionPane.OK_CANCEL_OPTION);
        if (option == JOptionPane.OK_OPTION) {
            dlManager.addTableColumn(jTable1, columnName.getText(), columnData.getText());
        } 
    }//GEN-LAST:event_btnAddColumnActionPerformed

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText("");
        final JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.setFileFilter(new FileNameExtensionFilter("Text Files", "txt"));
        int returnVal = fc.showOpenDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION){
            flSourceFile = fc.getSelectedFile();
            ArrayList<String> arrLines = dlManager.openTextFile(flSourceFile, Integer.parseInt(txtStartRow.getText()), Integer.parseInt(txtDisplayRows.getText()));
            for (String t: arrLines) {
                jTextArea1.append(t + "\n");
            } 
        } else {
            JOptionPane.showMessageDialog(null, "Open command cancelled by user.");
        }
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void txtHeaderRowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeaderRowsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeaderRowsActionPerformed

    private void btnColumnActionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColumnActionsActionPerformed
        // TODO add your handling code here:
        JComboBox columnAction = new JComboBox();
        columnAction.addItem("Split");
        columnAction.addItem("Join");
        columnAction.addItem("Duplicate");
        Object[] newField = {
            "Column Action: ", columnAction
        };
        int option = JOptionPane.showConfirmDialog(this.getParent(), newField, "Column Information", JOptionPane.OK_CANCEL_OPTION);
        if (option == JOptionPane.OK_OPTION) {
            switch (columnAction.getSelectedIndex()) {
                case 0:
                JTextField splitDelim = new JTextField();
                Object[] splitField = {
                    "Delimiter: ", splitDelim,
                };
                int optionSplit = JOptionPane.showConfirmDialog(this.getParent(), splitField, "Column Information", JOptionPane.OK_CANCEL_OPTION);
            }
        }
    }//GEN-LAST:event_btnColumnActionsActionPerformed

    private void txtColNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColNameActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        // TODO add your handling code here:
        final JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.setFileFilter(new FileNameExtensionFilter("Text Files", "txt"));
        int returnVal = fc.showOpenDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION){
            try {
                dlManager.exportFileFromTable(jTable1, fc.getSelectedFile(), arrDataColumn);
            } catch (IOException ex) {
                Logger.getLogger(PBCSAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnExportActionPerformed

    private void cbDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDataActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbDataActionPerformed

    private void jTable1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTable1PropertyChange
        // TODO add your handling code here:
        //System.out.println(evt.getPropertyName());
        if (evt.getPropertyName() == "model") {
            btnExport.setEnabled(true);
            arrDataColumn = new int[jTable1.getColumnCount()];
            arrPrefix = new String[jTable1.getColumnCount()];
            arrSuffix = new String[jTable1.getColumnCount()];
            arrFind = new String[jTable1.getColumnCount()];
            arrReplace = new String[jTable1.getColumnCount()];
        }
    }//GEN-LAST:event_jTable1PropertyChange

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTable1KeyPressed

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        updateColProps();
    }//GEN-LAST:event_jTable1KeyReleased

    private void btnPrevFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevFieldActionPerformed
        // TODO add your handling code here:
        jTable1.setColumnSelectionInterval(jTable1.getSelectedColumn() - 1, jTable1.getSelectedColumn() - 1);
        updateColProps();
    }//GEN-LAST:event_btnPrevFieldActionPerformed

    private void btnNextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextFieldActionPerformed
        // TODO add your handling code here:
        
        jTable1.setColumnSelectionInterval(jTable1.getSelectedColumn() + 1, jTable1.getSelectedColumn() + 1);
        updateColProps();
    }//GEN-LAST:event_btnNextFieldActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PBCSAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PBCSAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PBCSAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PBCSAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PBCSAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane MainTabbedPane;
    private javax.swing.ButtonGroup btgDelimiter;
    private javax.swing.JButton btnAddColumn;
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnColumnActions;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnLoadSQL;
    private javax.swing.JButton btnNextField;
    private javax.swing.JButton btnPrevField;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnUpdateField;
    private javax.swing.JCheckBox cbData;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblColName;
    private javax.swing.JLabel lblColumn;
    private javax.swing.JLabel lblDelim;
    private javax.swing.JLabel lblDisplayRows;
    private javax.swing.JLabel lblDisplayRows2;
    private javax.swing.JLabel lblFind;
    private javax.swing.JLabel lblPrefix;
    private javax.swing.JLabel lblReplace;
    private javax.swing.JLabel lblStartRow;
    private javax.swing.JLabel lblSuffix;
    private javax.swing.JPanel pnlColProps;
    private javax.swing.JPanel pnlDSMgmt;
    private javax.swing.JRadioButton rbComma;
    private javax.swing.JRadioButton rbCustom;
    private javax.swing.JRadioButton rbSpace;
    private javax.swing.JRadioButton rbTab;
    private javax.swing.JPanel tabDLMgr;
    private javax.swing.JPanel tabFSMgr;
    private javax.swing.JTextField txtColName;
    private javax.swing.JTextField txtCustDelim;
    private javax.swing.JTextField txtDisplayRows;
    private javax.swing.JTextField txtFind;
    private javax.swing.JTextField txtHeaderRows;
    private javax.swing.JTextField txtPrefix;
    private javax.swing.JTextField txtReplace;
    private javax.swing.JTextField txtStartRow;
    private javax.swing.JTextField txtSuffix;
    // End of variables declaration//GEN-END:variables
}
